# title: TRCS2001 Training Progress
# description: Daily log of my TRCS2001 technical training journey.
# remote_theme: just-the-docs/just-the-docs

# # You might also want to add these for Just The Docs
# search_enabled: true
# color_scheme: dark # or 'dark' if you prefer a dark theme by default


remote_theme: cotes2020/jekyll-theme-chirpy@v7.3.0 # Use a specific version

# Chirpy Theme specific settings (examples)
title: TRCS2001 Training Progress
description: Detailed daily log of my TRCS2001 technical training journey.
url: "https://yourusername.github.io"
baseurl: "/TRCS2001-Training-Progress"

# Profile
author: Your Name
avatar: /assets/img/avatar.png # Your profile image
twitter: your_twitter # Optional
github: your_github # Optional

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  # Chirpy specific plugins might need to be explicitly listed or managed by its setup

# Features
toc: true # Enable Table of Contents
darkMode: true # Enable dark mode toggle
search: true # Enable search
